'use strict';
const { Model, DataTypes } = require('sequelize');

const SapVbrpItem = (sequelize) => {
  class SapVbrpItem extends Model {
    static associate(models) {
      // Définir les associations ici si nécessaire
    }
  }
  
  SapVbrpItem.init({
  id: {
    type: DataTypes.BIGINT.UNSIGNED,
    primaryKey: true,
    autoIncrement: true,
  },
  MANDT: { type: DataTypes.CHAR(3), allowNull: false },
  VBELN: { type: DataTypes.CHAR(10), allowNull: false },
  POSNR: { type: DataTypes.CHAR(6), allowNull: false },
  UEPOS: DataTypes.CHAR(6),
  FKIMG: DataTypes.DECIMAL(18, 3),
  VRKME: DataTypes.CHAR(3),
  UMVKZ: DataTypes.DECIMAL(15, 3),
  UMVKN: DataTypes.DECIMAL(15, 3),
  MEINS: DataTypes.CHAR(3),
  SMENG: DataTypes.DECIMAL(18, 3),
  FKLMG: DataTypes.DECIMAL(18, 3),
  LMENG: DataTypes.DECIMAL(18, 3),
  NTGEW: DataTypes.DECIMAL(18, 3),
  BRGEW: DataTypes.DECIMAL(18, 3),
  GEWEI: DataTypes.CHAR(3),
  VOLUM: DataTypes.DECIMAL(18, 3),
  VOLEH: DataTypes.CHAR(3),
  GSBER: DataTypes.CHAR(4),
  PRSDT: DataTypes.CHAR(8),
  FBUDA: DataTypes.CHAR(8),
  KURSK: DataTypes.DECIMAL(15, 5),
  NETWR: DataTypes.DECIMAL(18, 2),
  VBELV: DataTypes.CHAR(10),
  POSNV: DataTypes.CHAR(6),
  VGBEL: DataTypes.CHAR(10),
  VGPOS: DataTypes.CHAR(6),
  VGTYP: DataTypes.CHAR(1),
  AUBEL: DataTypes.CHAR(10),
  AUPOS: DataTypes.CHAR(6),
  AUREF: DataTypes.CHAR(10),
  MATNR: DataTypes.CHAR(18),
  ARKTX: DataTypes.STRING(70),
  PMATN: DataTypes.CHAR(18),
  CHARG: DataTypes.CHAR(10),
  MATKL: DataTypes.CHAR(9),
  PSTYV: DataTypes.CHAR(4),
  POSAR: DataTypes.CHAR(4),
  PRODH: DataTypes.CHAR(18),
  VSTEL: DataTypes.CHAR(4),
  ATPKZ: DataTypes.CHAR(1),
  SPART: DataTypes.CHAR(2),
  POSPA: DataTypes.CHAR(6),
  WERKS: DataTypes.CHAR(4),
  ALAND: DataTypes.CHAR(3),
  WKREG: DataTypes.CHAR(2),
  WKCOU: DataTypes.CHAR(3),
  WKCTY: DataTypes.CHAR(4),
  TAXM1: DataTypes.CHAR(1),
  TAXM2: DataTypes.CHAR(1),
  TAXM3: DataTypes.CHAR(1),
  TAXM4: DataTypes.CHAR(1),
  TAXM5: DataTypes.CHAR(1),
  TAXM6: DataTypes.CHAR(1),
  TAXM7: DataTypes.CHAR(1),
  TAXM8: DataTypes.CHAR(1),
  TAXM9: DataTypes.CHAR(1),
  KOWRR: DataTypes.CHAR(1),
  PRSFD: DataTypes.CHAR(1),
  SKTOF: DataTypes.CHAR(1),
  SKFBP: DataTypes.DECIMAL(18, 2),
  KONDM: DataTypes.CHAR(2),
  KTGRM: DataTypes.CHAR(2),
  KOSTL: DataTypes.CHAR(10),
  BONUS: DataTypes.CHAR(1),
  PROVG: DataTypes.CHAR(1),
  EANNR: DataTypes.STRING(18),
  VKGRP: DataTypes.CHAR(3),
  VKBUR: DataTypes.CHAR(4),
  SPARA: DataTypes.CHAR(2),
  SHKZG: DataTypes.CHAR(1),
  ERNAM: DataTypes.CHAR(12),
  ERDAT: DataTypes.CHAR(8),
  ERZET: DataTypes.CHAR(6),
  BWTAR: DataTypes.CHAR(10),
  LGORT: DataTypes.CHAR(4),
  STAFO: DataTypes.CHAR(6),
  WAVWR: DataTypes.DECIMAL(18, 2),
  KZWI1: DataTypes.DECIMAL(18, 2),
  KZWI2: DataTypes.DECIMAL(18, 2),
  KZWI3: DataTypes.DECIMAL(18, 2),
  KZWI4: DataTypes.DECIMAL(18, 2),
  KZWI5: DataTypes.DECIMAL(18, 2),
  KZWI6: DataTypes.DECIMAL(18, 2),
  STCUR: DataTypes.DECIMAL(15, 5),
  UVPRS: DataTypes.CHAR(1),
  UVALL: DataTypes.CHAR(1),
  EAN11: DataTypes.STRING(18),
  PRCTR: DataTypes.CHAR(10),
  KVGR1: DataTypes.CHAR(2),
  KVGR2: DataTypes.CHAR(2),
  KVGR3: DataTypes.CHAR(2),
  KVGR4: DataTypes.CHAR(2),
  KVGR5: DataTypes.CHAR(2),
  MVGR1: DataTypes.CHAR(3),
  MVGR2: DataTypes.CHAR(3),
  MVGR3: DataTypes.CHAR(3),
  MVGR4: DataTypes.CHAR(3),
  MVGR5: DataTypes.CHAR(3),
  MATWA: DataTypes.CHAR(18),
  BONBA: DataTypes.DECIMAL(18, 2),
  KOKRS: DataTypes.CHAR(4),
  PAOBJNR: DataTypes.CHAR(10),
  PS_PSP_PNR: DataTypes.CHAR(8),
  AUFNR: DataTypes.CHAR(12),
  TXJCD: DataTypes.CHAR(15),
  CMPRE: DataTypes.DECIMAL(18, 2),
  CMPNT: DataTypes.CHAR(1),
  CUOBJ: DataTypes.CHAR(22),
  CUOBJ_CH: DataTypes.CHAR(22),
  KOUPD: DataTypes.CHAR(1),
  UEPCHA: DataTypes.CHAR(6),
  XCHAR: DataTypes.CHAR(1),
  ABRVW: DataTypes.CHAR(3),
  SERNR: DataTypes.CHAR(8),
  BZIRK_AUFT: DataTypes.CHAR(6),
  KDGRP_AUFT: DataTypes.CHAR(2),
  KONDA_AUFT: DataTypes.CHAR(2),
  LLAND_AUFT: DataTypes.CHAR(3),
  MPROK: DataTypes.CHAR(1),
  PLTYP_AUFT: DataTypes.CHAR(2),
  REGIO_AUFT: DataTypes.CHAR(3),
  VKORG_AUFT: DataTypes.CHAR(4),
  VTWEG_AUFT: DataTypes.CHAR(2),
  ABRBG: DataTypes.CHAR(8),
  PROSA: DataTypes.CHAR(1),
  UEPVW: DataTypes.CHAR(1),
  AUTYP: DataTypes.CHAR(1),
  STADAT: DataTypes.CHAR(8),
  FPLNR: DataTypes.CHAR(10),
  FPLTR: DataTypes.CHAR(6),
  AKTNR: DataTypes.CHAR(10),
  KNUMA_PI: DataTypes.CHAR(10),
  KNUMA_AG: DataTypes.CHAR(10),
  PREFE: DataTypes.CHAR(4),
  MWSBP: DataTypes.DECIMAL(18, 2),
  AUGRU_AUFT: DataTypes.CHAR(3),
  FAREG: DataTypes.CHAR(1),
  UPMAT: DataTypes.CHAR(18),
  UKONM: DataTypes.CHAR(1),
  CMPRE_FLT: DataTypes.DECIMAL(18, 6),
  ABFOR: DataTypes.CHAR(1),
  ABGES: DataTypes.INTEGER,
  J_1ARFZ: DataTypes.CHAR(5),
  J_1AREGIO: DataTypes.CHAR(3),
  J_1AGICD: DataTypes.CHAR(2),
  J_1ADTYP: DataTypes.CHAR(1),
  J_1ATXREL: DataTypes.CHAR(1),
  J_1BCFOP: DataTypes.CHAR(10),
  J_1BTAXLW1: DataTypes.CHAR(3),
  J_1BTAXLW2: DataTypes.CHAR(3),
  J_1BTXSDC: DataTypes.CHAR(3),
  BRTWR: DataTypes.DECIMAL(18, 2),
  WKTNR: DataTypes.CHAR(10),
  WKTPS: DataTypes.CHAR(6),
  RPLNR: DataTypes.CHAR(10),
  KURSK_DAT: DataTypes.CHAR(8),
  WGRU1: DataTypes.CHAR(2),
  WGRU2: DataTypes.CHAR(2),
  KDKG1: DataTypes.CHAR(3),
  KDKG2: DataTypes.CHAR(3),
  KDKG3: DataTypes.CHAR(3),
  KDKG4: DataTypes.CHAR(3),
  KDKG5: DataTypes.CHAR(3),
  VKAUS: DataTypes.CHAR(2),
  J_1AINDXP: DataTypes.CHAR(1),
  J_1AIDATEP: DataTypes.CHAR(8),
  KZFME: DataTypes.CHAR(1),
  MWSKZ: DataTypes.CHAR(2),
  VERTT: DataTypes.CHAR(1),
  VERTN: DataTypes.CHAR(10),
  SGTXT: DataTypes.STRING(50),
  DELCO: DataTypes.CHAR(1),
  BEMOT: DataTypes.CHAR(3),
  RRREL: DataTypes.CHAR(1),
  AKKUR: DataTypes.DECIMAL(15, 5),
  WMINR: DataTypes.CHAR(18),
  VGBEL_EX: DataTypes.CHAR(10),
  VGPOS_EX: DataTypes.CHAR(6),
  LOGSYS: DataTypes.CHAR(10),
  VGTYP_EX: DataTypes.CHAR(1),
  J_1BTAXLW3: DataTypes.CHAR(3),
  J_1BTAXLW4: DataTypes.CHAR(3),
  J_1BTAXLW5: DataTypes.CHAR(3),
  MSR_ID: DataTypes.CHAR(10),
  MSR_REFUND_CODE: DataTypes.CHAR(3),
  MSR_RET_REASON: DataTypes.CHAR(3),
  NRAB_KNUMH: DataTypes.CHAR(10),
  NRAB_VALUE: DataTypes.DECIMAL(18, 2),
  DISPUTE_CASE: DataTypes.BLOB,
  FUND_USAGE_ITEM: DataTypes.BLOB,
  FARR_RELTYPE: DataTypes.CHAR(1),
  CLAIMS_TAXATION: DataTypes.CHAR(1),
  KURRF_DAT_ORIG: DataTypes.CHAR(8),
  AUFPL: DataTypes.CHAR(10),
  APLZL: DataTypes.CHAR(8),
  DPCNR: DataTypes.CHAR(10),
  DCPNR: DataTypes.CHAR(3),
  DPNRB: DataTypes.CHAR(3),
  PEROP_BEG: DataTypes.CHAR(8),
  PEROP_END: DataTypes.CHAR(8),
  FUNDS: DataTypes.CHAR(10),
  FISTL: DataTypes.CHAR(16),
  FKBER: DataTypes.CHAR(16),
  GRANT_NBR: DataTypes.CHAR(20),
  PRS_WORK_PERIOD: DataTypes.CHAR(7),
  PPRCTR: DataTypes.CHAR(10),
  PARGB: DataTypes.CHAR(4),
  AUFPL_OAA: DataTypes.CHAR(10),
  APLZL_OAA: DataTypes.CHAR(8),
  CAMPAIGN: DataTypes.BLOB,
  COMPREAS: DataTypes.CHAR(2),
  UPDKZ: DataTypes.CHAR(1),
  SELKZ: DataTypes.CHAR(1),
  RKCOP: DataTypes.CHAR(1),
  GESMNG: DataTypes.DECIMAL(18, 3),
  KMEIN: DataTypes.CHAR(3),
  KPEIN2: DataTypes.DECIMAL(15, 3),
  NETPR: DataTypes.DECIMAL(18, 2),
  MSR_SPLIT_ID: DataTypes.CHAR(3),
  MSR_INSP_CODE: DataTypes.CHAR(3),
  PAYMNT: DataTypes.DECIMAL(18, 2),
}, {
  tableName: 'sap_vbrp_item',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  sequelize,
  modelName: 'SapVbrpItem',
  indexes: [
    { name: 'idx_vbrp_vbeln', fields: ['VBELN'] },
  ],
});

  return SapVbrpItem;
};

// Export the model function for Sequelize initialization
module.exports = SapVbrpItem;


