'use strict';
const { Model, DataTypes } = require('sequelize');

const SapVbrkHeader = (sequelize) => {
  class SapVbrkHeader extends Model {
    static associate(models) {
      // Définir les associations ici si nécessaire
    }
  }
  
  SapVbrkHeader.init({
  id: {
    type: DataTypes.BIGINT.UNSIGNED,
    primaryKey: true,
    autoIncrement: true,
  },
  MANDT: { type: DataTypes.CHAR(3), allowNull: false },
  VBELN: { type: DataTypes.CHAR(10), allowNull: false },
  FKART: DataTypes.CHAR(4),
  FKTYP: DataTypes.CHAR(1),
  VBTYP: DataTypes.CHAR(1),
  WAERK: DataTypes.CHAR(5),
  VKORG: DataTypes.CHAR(4),
  VTWEG: DataTypes.CHAR(2),
  KALSM: DataTypes.CHAR(6),
  KNUMV: DataTypes.CHAR(10),
  VSBED: DataTypes.CHAR(2),
  FKDAT: DataTypes.CHAR(8),
  BELNR: DataTypes.CHAR(10),
  GJAHR: DataTypes.CHAR(4),
  POPER: DataTypes.CHAR(3),
  KONDA: DataTypes.CHAR(2),
  KDGRP: DataTypes.CHAR(2),
  BZIRK: DataTypes.CHAR(6),
  PLTYP: DataTypes.CHAR(2),
  INCO1: DataTypes.CHAR(3),
  INCO2: DataTypes.STRING(50),
  EXPKZ: DataTypes.CHAR(1),
  RFBSK: DataTypes.CHAR(1),
  MRNKZ: DataTypes.CHAR(1),
  KURRF: DataTypes.DECIMAL(15, 5),
  CPKUR: DataTypes.CHAR(1),
  VALTG: DataTypes.CHAR(2),
  VALDT: DataTypes.CHAR(8),
  ZTERM: DataTypes.CHAR(4),
  ZLSCH: DataTypes.CHAR(1),
  KTGRD: DataTypes.CHAR(2),
  LAND1: DataTypes.CHAR(3),
  REGIO: DataTypes.CHAR(3),
  COUNC: DataTypes.CHAR(3),
  CITYC: DataTypes.CHAR(4),
  BUKRS: DataTypes.CHAR(4),
  TAXK1: DataTypes.CHAR(1),
  TAXK2: DataTypes.CHAR(1),
  TAXK3: DataTypes.CHAR(1),
  TAXK4: DataTypes.CHAR(1),
  TAXK5: DataTypes.CHAR(1),
  TAXK6: DataTypes.CHAR(1),
  TAXK7: DataTypes.CHAR(1),
  TAXK8: DataTypes.CHAR(1),
  TAXK9: DataTypes.CHAR(1),
  NETWR: DataTypes.DECIMAL(18, 2),
  ZUKRI: DataTypes.CHAR(7),
  ERNAM: DataTypes.CHAR(12),
  ERZET: DataTypes.CHAR(6),
  ERDAT: DataTypes.CHAR(8),
  STAFO: DataTypes.CHAR(6),
  KUNRG: DataTypes.CHAR(10),
  KUNAG: DataTypes.CHAR(10),
  MABER: DataTypes.CHAR(2),
  STWAE: DataTypes.CHAR(5),
  EXNUM: DataTypes.CHAR(10),
  STCEG: DataTypes.STRING(20),
  AEDAT: DataTypes.CHAR(8),
  SFAKN: DataTypes.CHAR(10),
  KNUMA: DataTypes.CHAR(10),
  FKART_RL: DataTypes.CHAR(4),
  FKDAT_RL: DataTypes.CHAR(8),
  KURST: DataTypes.CHAR(4),
  MSCHL: DataTypes.CHAR(2),
  MANSP: DataTypes.CHAR(1),
  SPART: DataTypes.CHAR(2),
  KKBER: DataTypes.CHAR(4),
  KNKLI: DataTypes.CHAR(10),
  CMWAE: DataTypes.CHAR(5),
  CMKUF: DataTypes.DECIMAL(15, 5),
  HITYP_PR: DataTypes.CHAR(1),
  BSTNK_VF: DataTypes.STRING(35),
  VBUND: DataTypes.CHAR(6),
  FKART_AB: DataTypes.CHAR(4),
  KAPPL: DataTypes.CHAR(2),
  LANDTX: DataTypes.CHAR(3),
  STCEG_H: DataTypes.CHAR(2),
  STCEG_L: DataTypes.CHAR(2),
  XBLNR: DataTypes.STRING(50),
  ZUONR: DataTypes.STRING(50),
  MWSBK: DataTypes.DECIMAL(18, 2),
  LOGSYS: DataTypes.CHAR(10),
  FKSTO: DataTypes.CHAR(1),
  XEGDR: DataTypes.CHAR(1),
  RPLNR: DataTypes.CHAR(10),
  LCNUM: DataTypes.STRING(35),
  J_1AFITP: DataTypes.CHAR(2),
  KURRF_DAT: DataTypes.CHAR(8),
  AKWAE: DataTypes.CHAR(5),
  AKKUR: DataTypes.DECIMAL(15, 5),
  KIDNO: DataTypes.STRING(35),
  BVTYP: DataTypes.CHAR(2),
  NUMPG: DataTypes.CHAR(3),
  BUPLA: DataTypes.CHAR(4),
  VKONT: DataTypes.CHAR(12),
  FKK_DOCSTAT: DataTypes.CHAR(1),
  NRZAS: DataTypes.CHAR(3),
  SPE_BILLING_IND: DataTypes.CHAR(1),
  VTREF: DataTypes.CHAR(10),
  FK_SOURCE_SYS: DataTypes.CHAR(10),
  FKTYP_CRM: DataTypes.CHAR(1),
  STGRD: DataTypes.CHAR(2),
  J_1TPBUPL: DataTypes.CHAR(4),
  DPC_REL: DataTypes.CHAR(1),
  MNDID: DataTypes.CHAR(10),
  PAY_TYPE: DataTypes.CHAR(2),
  SEPON: DataTypes.CHAR(1),
  MNDVG: DataTypes.CHAR(10),
  SPPAYM: DataTypes.CHAR(4),
  SPPORD: DataTypes.STRING(35),
  UPDKZ: DataTypes.CHAR(1),
  HIPOS: DataTypes.CHAR(6),
  SELKZ: DataTypes.CHAR(1),
  NAMRG: DataTypes.STRING(70),
  XCPDK: DataTypes.CHAR(1),
  ADRNR: DataTypes.CHAR(10),
  UVALS: DataTypes.CHAR(1),
  UVPRS: DataTypes.CHAR(1),
  BOKRE: DataTypes.CHAR(1),
  NUMKI: DataTypes.CHAR(15),
  VBPANZ: DataTypes.INTEGER,
  RRREL: DataTypes.CHAR(1),
  SFAKN_RD: DataTypes.CHAR(10),
  MSR_ACTIVE: DataTypes.CHAR(1),
  STCEG: DataTypes.STRING(20),
}, {
  tableName: 'sap_vbrk_header',
  timestamps: false,
  sequelize,
  modelName: 'SapVbrkHeader',
  indexes: [
    { name: 'idx_vbrk_vbeln', fields: ['VBELN'] },
    { name: 'idx_vbrk_knumv', fields: ['KNUMV'] },
  ],
});

  return SapVbrkHeader;
};

// Export the model function for Sequelize initialization
module.exports = SapVbrkHeader;
